name: Build and Deploy Documents

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install FORD to build and deploy documents
        run: |
          sudo apt-get update
          sudo pip install ford

      - name: Check the status of FORD
        run: ford --version

      - name: Build the documents
        run: ford ford.md

      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: doc
          if-no-files-found: error

      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@4.1.0
        if: ${{ github.event_name == 'push'  &&  github.ref == 'refs/heads/main' }}
        with:
          
          branch: github-pages
          folder: doc
